import 'package:flutter/material.dart';

class CopyrightNoticePage extends StatelessWidget {
  const CopyrightNoticePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.black,
        title: Text('Copyright Notice'),
      ),
      body: SingleChildScrollView(
        child: Text(
          _text,
          style: TextStyle(fontSize: 16.0, color: Colors.grey),
        ),
      ),
    );
  }
}

const _text = '''

Copyright Notice:
"Copyright © 2025 Zhang Qing. All rights reserved."
"Game images are generated by artificial intelligence, with post-processing adjustments by the developer."
"Portions of the sound files in this game are from pixabay.com, used under their respective license terms."
Developer Information:
  "Developer: Zhang Qing."
"Contact: zq1982084034@gmail.com."
"Development Platform: Flutter."
Legal Disclaimer (Optional):
"This game's content is for entertainment purposes only and does not represent any specific viewpoints or positions."
"The developer assumes no responsibility for the accuracy, completeness, or applicability of this game's content."


版權聲明：
「版權所有 © 2025 張慶。保留一切權利。」
「本遊戲圖像由人工智慧生成，並經開發者後製調整。」
「本遊戲部分聲音檔案來自 pixabay.com，依其授權條款使用。」
開發者資訊：
「開發者：張慶。」
「聯繫方式：zq1982084034@gmail.com。」
「開發平台：Flutter。」
法律聲明：
「本遊戲內容僅供娛樂，不代表任何特定觀點或立場。」
「開發者對本遊戲內容之準確性、完整性或適用性不承擔任何責任。」


版权声明：
  版权所有 © 2025 张庆。保留一切权利。
  本游戏图像由人工智能生成，并经开发者后期调整。
  本游戏部分音频文件来自 pixabay.com，并根据其授权条款使用。
开发者信息：
  开发者：张庆。
  联系方式：zq1982084034@gmail.com。
  开发平台：Flutter。
法律声明：
  本游戏内容仅供娱乐，不代表任何特定观点或立场。
  开发者对本游戏内容的准确性、完整性或适用性不承担任何责任。

''';
